# Generated by Django 6.0.3 on 2026-06-01 20:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('categoria', models.CharField(choices=[('soporte', 'Soporte técnico'), ('premium', 'Plan premium'), ('asesoramiento', 'Asesoramiento financiero'), ('problema', 'Problema técnico'), ('otro', 'Otro')], default='soporte', max_length=20)),
                ('asunto', models.CharField(max_length=150, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('respondido', 'Respondido'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_contacto', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consulta de contacto',
                'verbose_name_plural': 'Consultas de contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
