# Generated by Django 6.0.3 on 2026-10-05 10:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_notificacion'),
        ('vistaprevia', '0010_producto_cobertura_datos_quant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('nombre_snapshot', models.CharField(max_length=120)),
                ('simbolo_snapshot', models.CharField(max_length=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda_activo', models.CharField(max_length=3)),
                ('importe_demo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda_cobro', models.CharField(default='ARS', max_length=3)),
                ('estado', models.CharField(choices=[('CREATED', 'Creada'), ('PENDING', 'Pendiente'), ('ACTION_REQUIRED', 'Accion requerida'), ('APPROVED', 'Acreditada (prueba)'), ('REJECTED', 'Rechazada'), ('CANCELLED', 'Cancelada'), ('ERROR', 'Error recuperable'), ('REFUNDED', 'Reembolsada'), ('PARTIALLY_REFUNDED', 'Reembolso parcial'), ('REVIEW_REQUIRED', 'Revision requerida')], default='CREATED', max_length=24)),
                ('environment', models.CharField(default='test', max_length=10)),
                ('submission_key', models.UUIDField(unique=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mp_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('checkout_url', models.URLField(blank=True, max_length=1000)),
                ('checkout_payload', models.JSONField(default=dict)),
                ('mp_status', models.CharField(blank=True, max_length=64)),
                ('mp_status_detail', models.CharField(blank=True, max_length=128)),
                ('mp_user_id', models.CharField(blank=True, max_length=64)),
                ('mp_application_id', models.CharField(blank=True, max_length=64)),
                ('mp_updated_us', models.BigIntegerField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
                ('aprobada', models.DateTimeField(blank=True, null=True)),
                ('reembolsada', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('ultimo_error', models.CharField(blank=True, max_length=64)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vistaprevia.producto')),
                ('inversion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orden_pago', to='usuarios.inversionsimulada')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creada'],
            },
        ),
        migrations.CreateModel(
            name='EventoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=20)),
                ('resultado', models.CharField(max_length=64)),
                ('estado_anterior', models.CharField(blank=True, max_length=24)),
                ('estado_nuevo', models.CharField(blank=True, max_length=24)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='pagos.ordenpago')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('estado', models.CharField(max_length=64)),
                ('detalle', models.CharField(blank=True, max_length=128)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(max_length=3)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='pagos.ordenpago')),
            ],
        ),
        migrations.AddIndex(
            model_name='ordenpago',
            index=models.Index(fields=['estado', 'actualizada'], name='pago_estado_fecha'),
        ),
        migrations.AddIndex(
            model_name='ordenpago',
            index=models.Index(fields=['usuario', 'creada'], name='pago_usuario_fecha'),
        ),
        migrations.AddConstraint(
            model_name='ordenpago',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 1), ('cantidad__lte', 100000)), name='pago_cantidad_valida'),
        ),
        migrations.AddConstraint(
            model_name='ordenpago',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gt', 0)), name='pago_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ordenpago',
            constraint=models.CheckConstraint(condition=models.Q(('importe_demo__gt', 0)), name='pago_demo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ordenpago',
            constraint=models.CheckConstraint(condition=models.Q(('environment', 'test'), ('moneda_cobro', 'ARS')), name='pago_solo_demo_ars'),
        ),
        migrations.AddConstraint(
            model_name='pagoproveedor',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='proveedor_importe_valido'),
        ),
    ]
