# Generated by Django 6.0.3 on 2026-04-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0003_alter_producto_options_remove_producto_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='bolsa',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Bolsa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='capitalizacion_mercado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Capitalización de mercado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='activos/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pais',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio actual'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='producto',
            name='simbolo',
            field=models.CharField(default='SINM', max_length=10, unique=True, verbose_name='Símbolo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='variacion_diaria',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Variación diaria (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='volumen',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Volumen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=120, verbose_name='Nombre del activo'),
        ),
    ]
