# Generated by Django 6.0.3 on 2026-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0004_alter_producto_options_producto_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='simbolo',
            field=models.CharField(default='SINM', max_length=10, verbose_name='Símbolo'),
        ),
    ]
