# Generated by Django 6.0.3 on 2026-04-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0005_alter_producto_simbolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar estadounidense'), ('ARS', 'Peso argentino'), ('EUR', 'Euro')], default='USD', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='producto',
            name='recomendacion',
            field=models.CharField(choices=[('comprar', 'Comprar'), ('mantener', 'Mantener'), ('vender', 'Vender')], default='mantener', max_length=10, verbose_name='Recomendación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='riesgo',
            field=models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], default='medio', max_length=10, verbose_name='Nivel de riesgo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_activo',
            field=models.CharField(choices=[('accion', 'Acción'), ('etf', 'ETF'), ('crypto', 'Criptomoneda'), ('indice', 'Índice'), ('bono', 'Bono')], default='accion', max_length=20, verbose_name='Tipo de activo'),
        ),
    ]
