# Generated by Django 6.0.3 on 2026-04-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0006_producto_moneda_producto_recomendacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='apertura',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio de apertura'),
        ),
        migrations.AddField(
            model_name='producto',
            name='beta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Beta'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cierre_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Cierre anterior'),
        ),
        migrations.AddField(
            model_name='producto',
            name='confianza_modelo',
            field=models.PositiveIntegerField(default=50, verbose_name='Confianza del modelo (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='dividendo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Dividendo (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='eps',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='EPS'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_revision',
            field=models.DateField(blank=True, null=True, verbose_name='Última revisión'),
        ),
        migrations.AddField(
            model_name='producto',
            name='industria',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Industria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='maximo_52_semanas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Máximo 52 semanas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='maximo_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Máximo del día'),
        ),
        migrations.AddField(
            model_name='producto',
            name='minimo_52_semanas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Mínimo 52 semanas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='minimo_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Mínimo del día'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nota_analista',
            field=models.TextField(blank=True, default='', verbose_name='Nota del analista'),
        ),
        migrations.AddField(
            model_name='producto',
            name='pe_ratio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='P/E Ratio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_objetivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio objetivo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='puntaje_quant',
            field=models.PositiveIntegerField(default=50, verbose_name='Puntaje QuantEdge'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tesis_inversion',
            field=models.TextField(blank=True, default='', verbose_name='Tesis de inversión'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ticker_externo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Ticker externo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='variacion_mensual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Variación mensual (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='variacion_semanal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Variación semanal (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='volumen_promedio',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Volumen promedio'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('USD', 'Dólar estadounidense'), ('ARS', 'Peso argentino'), ('EUR', 'Euro'), ('GBP', 'Libra esterlina')], default='USD', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='recomendacion',
            field=models.CharField(choices=[('comprar', 'Comprar'), ('mantener', 'Mantener'), ('vender', 'Vender'), ('observar', 'Observar')], default='mantener', max_length=10, verbose_name='Recomendación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_activo',
            field=models.CharField(choices=[('accion', 'Acción'), ('etf', 'ETF'), ('crypto', 'Criptomoneda'), ('indice', 'Índice'), ('bono', 'Bono'), ('fondo', 'Fondo')], default='accion', max_length=20, verbose_name='Tipo de activo'),
        ),
    ]
