# Generated by Django 6.0.3 on 2026-08-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0007_producto_apertura_producto_beta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado_sincronizacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('sincronizado', 'Sincronizado'), ('error', 'Error'), ('desactivado', 'Desactivado')], default='pendiente', max_length=20, verbose_name='Estado de sincronización'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultima_sincronizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronización exitosa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultimo_intento_sincronizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último intento de sincronización'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_datos',
            field=models.CharField(choices=[('twelve_data', 'Twelve Data')], default='twelve_data', max_length=30, verbose_name='Proveedor de datos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sincronizacion_automatica',
            field=models.BooleanField(default=True, help_text='Permite que este activo pueda ser actualizado automáticamente por tareas programadas.', verbose_name='Sincronización automática'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ultimo_error_sincronizacion',
            field=models.TextField(blank=True, default='', verbose_name='Último error de sincronización'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['simbolo'], name='qe_producto_simbolo_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['ticker_externo'], name='qe_producto_ticker_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo', 'sincronizacion_automatica'], name='qe_producto_sync_idx'),
        ),
    ]
