# Generated by Django 6.0.3 on 2026-08-27 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0008_producto_estado_sincronizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y hora de cotización')),
                ('intervalo', models.CharField(choices=[('1min', '1 minuto'), ('5min', '5 minutos'), ('15min', '15 minutos'), ('30min', '30 minutos'), ('45min', '45 minutos'), ('1h', '1 hora'), ('2h', '2 horas'), ('4h', '4 horas'), ('1day', '1 día'), ('1week', '1 semana'), ('1month', '1 mes')], default='1day', max_length=20, verbose_name='Intervalo')),
                ('apertura', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Apertura')),
                ('maximo', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Máximo')),
                ('minimo', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Mínimo')),
                ('cierre', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='Cierre')),
                ('volumen', models.PositiveBigIntegerField(default=0, verbose_name='Volumen')),
                ('proveedor', models.CharField(choices=[('twelve_data', 'Twelve Data')], default='twelve_data', max_length=30, verbose_name='Proveedor')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_historicas', to='vistaprevia.producto', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cotización histórica',
                'verbose_name_plural': 'Cotizaciones históricas',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['activo', 'fecha_hora'], name='qe_hist_asset_date_idx'), models.Index(fields=['activo', 'intervalo', 'fecha_hora'], name='qe_hist_interval_idx')],
                'constraints': [models.UniqueConstraint(fields=('activo', 'fecha_hora', 'intervalo', 'proveedor'), name='qe_unique_historical_quote')],
            },
        ),
    ]
