# Generated by Django 6.0.3 on 2026-09-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0009_cotizacionhistorica'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cobertura_datos_quant',
            field=models.PositiveIntegerField(default=0, help_text='Representa la disponibilidad de datos históricos utilizados por el motor cuantitativo. No representa probabilidad de rendimiento futuro.', verbose_name='Cobertura de datos QuantEdge (%)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_ultimo_score_quant',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último cálculo del score QuantEdge'),
        ),
        migrations.AddField(
            model_name='producto',
            name='version_score_quant',
            field=models.CharField(blank=True, default='v1', max_length=20, verbose_name='Versión del motor QuantEdge'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='confianza_modelo',
            field=models.PositiveIntegerField(default=50, help_text='Reservado para la confianza de futuros modelos predictivos o de inteligencia artificial.', verbose_name='Confianza del modelo (%)'),
        ),
    ]
