# Generated by Django 6.0.3 on 2026-04-28 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vistaprevia', '0007_producto_apertura_producto_beta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(blank=True, default='', verbose_name='Pregunta')),
                ('respuesta', models.TextField(verbose_name='Respuesta IA')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consulta')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_ia', to='vistaprevia.producto', verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_ia', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consulta IA',
                'verbose_name_plural': 'Consultas IA',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InversionSimulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de compra')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones_simuladas', to='vistaprevia.producto', verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones_simuladas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Inversión simulada',
                'verbose_name_plural': 'Inversiones simuladas',
                'ordering': ['-fecha_compra'],
            },
        ),
    ]
