# Generated by Django 6.0.3 on 2026-05-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversionsimulada',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
