# Generated by Django 6.0.3 on 2026-06-01 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_inversionsimulada_activa'),
        ('vistaprevia', '0007_producto_apertura_producto_beta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultaia',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_ia', to='vistaprevia.producto'),
        ),
        migrations.AlterField(
            model_name='consultaia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas_ia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inversionsimulada',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones_simuladas', to='vistaprevia.producto'),
        ),
        migrations.AlterField(
            model_name='inversionsimulada',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones_simuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil')),
                ('nombre_completo', models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, default='', max_length=30, verbose_name='Teléfono')),
                ('pais', models.CharField(blank=True, default='Argentina', max_length=80, verbose_name='País')),
                ('perfil_inversor', models.CharField(choices=[('conservador', 'Conservador'), ('moderado', 'Moderado'), ('agresivo', 'Agresivo')], default='moderado', max_length=20, verbose_name='Perfil inversor')),
                ('capital_demo', models.DecimalField(decimal_places=2, default=25000.0, max_digits=12, verbose_name='Capital demo')),
                ('biografia', models.TextField(blank=True, default='', verbose_name='Biografía')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
    ]
