# Generated by Django 6.0.3 on 2026-06-08 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_consultaia_activo_alter_consultaia_usuario_and_more'),
        ('vistaprevia', '0007_producto_apertura_producto_beta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha agregado')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_favoritos', to='vistaprevia.producto', verbose_name='Activo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos_favoritos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Activo favorito',
                'verbose_name_plural': 'Activos favoritos',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('usuario', 'activo')},
            },
        ),
    ]
